### ISSUE TITLE
[feature] : Provide documentation website in the repo's description 

### ISSUE THREAD

**Issue by k8s-dev** [litmuschaos/v1-litmus-docs#242]
Currently only description field is populated in the litmus-docs repo.

Proposal is to populate website field as well, ie.
Description: Documentation for the Litmus Chaos Project      website: https://docs.litmuschaos.io/ 

This way it is faster for dev/users to browse around the docs.

**Comment by k8s-dev** [comment]
screenshot:
![litmuswebsite](https://user-images.githubusercontent.com/57744184/77564528-e152f600-6ee8-11ea-9d89-e2e4b2f4512a.png)

**Comment by ksatchit** [comment]
Done!! Thanks for noting this @k8s-dev !
