### ISSUE TITLE
The search functionality on the litmus-docs is not working

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/v1-litmus-docs#272]

**Comment by ksatchit** [comment]
cc: @k8s-dev @rajdas98

**Comment by k8s-dev** [comment]
https://docusaurus.io/docs/en/search#enabling-the-search-bar specifies to submit the doc website(https://docs.litmuschaos.io) to https://docsearch.algolia.com/ for getting API key and index name. 

I have sent the form, will work on this once i hear back.

**Comment by ksatchit** [comment]
Cool! Thanks @k8s-dev !

**Comment by k8s-dev** [comment]
Created PR : https://github.com/litmuschaos/litmus-docs/pull/277

**Comment by ksatchit** [comment]
This is fixed by #277
