### ISSUE TITLE
Add docs for node-poweroff experiment 

### ISSUE THREAD

**Issue by ksatchit** [litmuschaos/v1-litmus-docs#425]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

**What happened**:

- The node-restart docs here https://docs.litmuschaos.io/docs/next/node-restart/  can be updated OR a new experiment doc created to factor in the node-poweroff chaos. 

- Also, this section in the prerequisites can be elaborated a bit more (say, example steps for generating the key pair and how to use it): 

![image](https://user-images.githubusercontent.com/21166217/102103515-1c200400-3e53-11eb-9796-2110e05e9a3f.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by ksatchit** [comment]
cc: @jordigilh

**Comment by jordigilh** [comment]
@ksatchit I can add the documentation for this one. Can you assign it to me instead?

**Comment by ksatchit** [comment]
Sure :) That would be great!! Just invited you into the litmuschaos org @jordigilh

**Comment by jordigilh** [comment]
Thanks!

**Comment by jordigilh** [comment]
@ksatchit do you think it is possible to close this issue now that the documentation has been updated?

**Comment by ksatchit** [comment]
Yes! Fixed via https://github.com/litmuschaos/litmus-docs/pull/434
