### ISSUE TITLE
pod-memory-hog/#prerequisites

### ISSUE THREAD

**Issue by rbalagopalakrishna** [litmuschaos/v1-litmus-docs#468]
https://docs.litmuschaos.io/docs/pod-memory-hog/#prerequisites

In the prerequisites, the doc saying that: Cluster must run docker container runtime.

I see that pod-memory-hog can be done on containerd environment also using litmus library.

please give some clarity on this.

**Comment by ispeakc0de** [comment]
Hi @rbalagopalakrishna,

Yes, we support two chaoslibs for this experiment:
litmus: it supports docker, containerd, and crio container runtime
pumba: it supports only docker runtime

Docs need to be updated. Thanks for pointing it out.

**Comment by uditgaurav** [comment]
Hi @rbalagopalakrishna , The pod-memory-hog experiment supports both runtimes docker and contained. You can set the `SOCKET_PATH` and `CONTAINER_RUNTIME` in the [experiment.yml](https://github.com/litmuschaos/chaos-charts/blob/master/charts/generic/pod-memory-hog/experiment.yaml) for the experiment accordingly.

The experiment uses two different libs. `litmus` and `pumba`.

- `litmus` lib supports both docker and contained cluster runtime.
- `Pumba` lib only supports containerd runtime.

The difference between the libs is in the way of injecting chaos.

**Comment by rbalagopalakrishna** [comment]
Thank you for your support.


Thanks
Bala Ramanadam.
