### ISSUE TITLE
`python-software-properties` has been replaced with `software-properties-common` in README.md

### ISSUE THREAD

**Issue by avinash-rath** [litmuschaos/v1-litmus-docs#54]
The `python-software-properties` has been replaced with `software-properties-common`.

Also, after the clone the user might want to run an `npm install` before the `npm start`.

**Comment by avinash-rath** [comment]
> Also, after the clone the user might want to run an `npm install` before the `npm start`.

Otherwise the .gitignore can be changed so that the node modules are also pushed to the repo.

**Comment by avinash-rath** [comment]
#55

**Comment by imrajdas** [comment]
PR merged
/close
