### ISSUE TITLE
Fix URL's in Getting Started Documentation, Add Padding to code Snippets, Fix the Copy Button Overlapping content

### ISSUE THREAD

**Issue by satyajitghana** [litmuschaos/v1-litmus-docs#66]
some URL's broken in the documentation
``kubectl create -f https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiment.yaml ``

change to
``kubectl create -f https://raw.githubusercontent.com/litmuschaos/chaos-charts/master/charts/generic/experiments.yaml ``

- Broken URL: https://docs.litmuschaos.io/docs/0.6.0/getstarted/example.html
same link is broken in other versions

- The copy button hides part of the code, add padding to the container.

Output container isn't ``monospaced``

**Comment by ksatchit** [comment]
Fixed in 0.8 release
